#spring.application.name=jp-capacitacao-2026
#spring.jpa.hibernate.ddl-auto=update
spring:
  application:
    name: jp-capacitacao-2026

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: ${URL_DB:jdbc:oracle:thin:@//localhost:1521/XE}
    username: ${USERNAME_DB:JP_JAVAWEB}
    password: ${PASSWORD_DB:JP_JAVAWEB}
    driverClassName: oracle.jdbc.driver.OracleDriver

server:
  port: 9090